import { ReactNode } from "react";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata = {
  title: {
    default: "Next.js | Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
